### ISSUE TITLE
Option to exclude peer dependencies + package composition

### ISSUE THREAD

**Issue by atomiks** [okikio/bundlejs#22]
`@floating-ui/react-dom` is ~5 kB with everything exported, but displays 52.2 kB because React+React DOM are included in the bundle. 

Further, a breakdown of the package composition would be good (like `webpack-bundle-analyzer`) to see which dependencies are the largest of a package. That would make this more obvious

**Comment by atomiks** [comment]
I just saw #13 is about `peerDependencies`. Clicking the settings icon and adding them to the `"external"` key works:

```json
"esbuild": {
  "external": ["react", "react-dom"],
```

@okikio maybe add this to the docs?

The package composition feature would still be cool though 👍

**Comment by okikio** [comment]
I'm currently working on a massive blog posts that will detail all the hidden features in bundlejs. 

> You may not know this but you can also use aliases in bundlejs.
> ```json
> {
>     "aliases": { "@okikio/animate": "react-dom" }
> }
> ```

**Comment by okikio** [comment]
The source of difficulty in implementing a package composition analyzer is the creation of a graph, I'd appreciate it if you or really anyone could design a graph for it, it's quite a bit of work....Lol 😅.

**Comment by atomiks** [comment]
@okikio 😰 I have no experience in this area so if it's too hard feel free to close

**Comment by okikio** [comment]
I've put out a call to collaborate, maybe share it around with other peeps and lets see if we can make magic happen. 

[twitter.com/jsbundle/status/1520921432112443392](https://twitter.com/jsbundle/status/1520921432112443392?s=20&t=NHOkSCG_D1ftJ6MuBhh9rg)

**Comment by okikio** [comment]
@atomiks I've found someone willing to work on collaborating to implement a package composition graph. Also, I've added docs about aliases and externals to bundle 
* https://bundlejs.com/#aliases
* https://bundlejs.com/#externals

**Comment by okikio** [comment]
Since, this feature is already public, I'll close this
