### ISSUE TITLE
npms.io is flaky

### ISSUE THREAD

**Issue by valtism** [okikio/bundlejs#26]
Having real issues trying to get search results today. I think it would be better to switch back to `registry.npmjs.com` for the mean time (or permanently, was it switched for query speed?)

**Comment by okikio** [comment]
I initially used `npms.io` to get more accurate search results, but I'm now permanently switching back to `registry.npmjs.com` because `npms.io` isn't reliable.

**Comment by valtism** [comment]
Nice. Does `monaco.ts` also need to have `result.results` changed to `result.objects`?

**Comment by okikio** [comment]
Woops! I forgot about `monaco.ts`, but it should now be fixed.
