### ISSUE TITLE
Badges with package size

### ISSUE THREAD

**Issue by Demivan** [okikio/bundlejs#30]
shields.io has Bundlephobia integration.

Lodash: ![lodash size](https://img.shields.io/bundlephobia/min/lodash?style=for-the-badge)

Would be nice to have something similar with bundlejs.

**Comment by okikio** [comment]
I'll get on that

**Comment by wooorm** [comment]
See also https://github.com/okikio/bundlejs/discussions/29.

P.S. I’m still very interested in badges :)

**Comment by okikio** [comment]
I've started working on it. A beta version should be out in a couple days

**Comment by okikio** [comment]
There is now a beta API you can try out, https://bundlejs.com/api?q=react, it is very much not production ready and very experimental, but try it out and tell me what you think.

**Comment by okikio** [comment]
Badges WIP https://github.com/badges/shields/issues/8266

**Comment by wooorm** [comment]
Sweet, thanks for working on this!
(Btw, maybe this is intentional, but FYI: your branch is not a PR to upstream yet.)

**Comment by okikio** [comment]
That's because I've still got some stuff I've gotta do before making a fully fledged pr.

**Comment by okikio** [comment]
So, I've got a beta version of badges out. There are some bugs in the Vercel Serverless functions that cause the badge to not be generated properly for large bundles to which the bundlejs website can handle.

<a href="https://bundlejs.com/api/badge?q=react">

![bundlejs bundle of react](https://bundlejs.com/api/badge?q=react) 

</a>

You can try it out, using

```md
![bundlejs bundle of react](https://bundlejs.com/api/badge?q=react) 
```

**Comment by Demivan** [comment]
![image](https://user-images.githubusercontent.com/2339406/182792700-3474d3c8-8b03-481b-b0c4-a1f17e0b774a.png)

https://github.com/fluent-vue/fluent-vue it works. Function timed out few times.
Some comments:
- other badges have label on the left side
- bundlejs label could be confusing. bundlephobia has just `minified size` as a label ![](https://badgen.net/bundlephobia/min/vue)

Side note https://bundlejs.com/ is broken. Editor never finishes loading

**Comment by okikio** [comment]
Thanks @Demivan , yeah i can totaly change the order of the file size to bundlejs text. 

P.S. I've fixed bundlejs' infinite loading

**Comment by wooorm** [comment]
I tried to update some things but I’m getting errors it seems:

For: https://bundlejs.com/api/badge?q=rehype-raw

```json
{"error":"TypeError: Cannot read properties of undefined (reading 'contents')"}
```

For: https://bundlejs.com/api/badge?q=micromark

```
This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.
```

(the vercel 504 gateway timeout error)

**Comment by okikio** [comment]
@wooorm Thanks for that, I'm working on fixing this issue

**Comment by okikio** [comment]
Good news I've got an even better version releasing this week. It supports badges, complex modules, can return the bundle metafile for https://esbuild.github.io/analyze/, and even gives you the fully bundled code, etc... 

Get excited, I'm just waiting for the DNS propagation...before lauching

**Comment by okikio** [comment]
A little late, but it's now out...badges 👏

[![spring-easing's badge](https://deno.bundlejs.com/?q=spring-easing&badge=detailed&badge-style=for-the-badge)](https://bundlejs.com/?q=spring-easing)

```md
[![spring-easing's badge](https://deno.bundlejs.com/?q=spring-easing&badge=detailed&badge-style=for-the-badge)](https://bundlejs.com/?q=spring-easing)
```

https://twitter.com/jsbundle/status/1634457855746011136?s=20

cc @wooorm

**Comment by okikio** [comment]
You can also now import bundled bundlejs files and polyfill them using the bundlejs API

**Comment by wooorm** [comment]
Awesome!

Two Qs:
- I was missing some docs on what options are available to build the urls
- How come the esbuild CLI gives me 15kb, but bundlejs gives me 27kb? 👀:
  ```sh
  $ ./node_modules/.bin/esbuild micromark --color=true --global-name=BundledCode --log-level=info --target=esnext --format=esm --bundle --minify --tree-shaking=true --platform=browser | gzip-size
  15.2 kB
  ```
  https://deno.bundlejs.com/?q=micromark

  n.b., my assumption is that the platform=browser isn’t actually set. Changing it to `--platform=node` does report 27kb. In Node, a bunch of [extra code](https://github.com/wooorm/decode-named-character-reference/blob/4347630741f82d7d4c7fb38763ba158951b2a1be/package.json#L32-L40) is loaded which isn’t needed if the DOM is available

**Comment by okikio** [comment]
@wooorm It's possible it's grabbing the cjs format of one of the files, from what I can see of the bundle analysis it seems to be grabbing all the right files? Maybe, I'm missing something? 🤔 https://deno.bundlejs.com/?q=micromark&analysis

**Comment by wooorm** [comment]
I can’t open that url: `{"error":"TypeError: worker.postMessage is not a function"}`

**Comment by okikio** [comment]
I'll have to look into thus, thanks for taking the time to take a look

**Comment by okikio** [comment]
The bundle analysis error should now be fixed. Please take a look

**Comment by okikio** [comment]
@wooorm Fixed. It should now be using `index.dom.js`

**Comment by wooorm** [comment]
Sweet, works well!

![](https://deno.bundlejs.com/?q=micromark&badge)

What do you think about using `minzipped size` on the left (and removing `(gzip)` on the right)? That’s what I get for shields.io currently:

```
![](https://img.shields.io/bundlephobia/minzip/preact.svg)
![](https://img.shields.io/bundlephobia/min/preact.svg)
```

![](https://img.shields.io/bundlephobia/minzip/preact.svg)
![](https://img.shields.io/bundlephobia/min/preact.svg)

**Comment by okikio** [comment]
Sure, I can do that

**Comment by okikio** [comment]
By default it shows the gzipped size, you can use a JSON endpoint shield in the meantime 

![Custom endpoint](https://img.shields.io/badge/dynamic/json?color=blue&label=bundlejs-(min)&query=$.size.uncompressedSize&url=https://deno.bundlejs.com/?q=react)

```md
![](https://img.shields.io/badge/dynamic/json?color=blue&label=bundlejs-(min)&query=$.size.uncompressedSize&url=https://deno.bundlejs.com/?q=react)
```

**Comment by MellKam** [comment]
@okikio Thank you!

**Comment by okikio** [comment]
@Demivan Does the badge API work for you? Can I mark this pr as complete?

**Comment by Demivan** [comment]
It timed out few times but it is working now.

Only thing is that I cannot find is how to properly encode string with esbuild config, so shields.io does not complain about wrong url.

```md
![](https://img.shields.io/badge/dynamic/json?color=blue&label=fluent-vue&suffix=%20(bundlejs)&query=$.size.size&url=https://deno.bundlejs.com/?q=fluent-vue)
```

![](https://img.shields.io/badge/dynamic/json?color=blue&label=fluent-vue&suffix=%20(bundlejs)&query=$.size.size&url=https://deno.bundlejs.com/?q=fluent-vue)

It either ignores is:
```md
![](https://img.shields.io/badge/dynamic/json?label=fluent-vue&suffix=%20(bundlejs)&query=$.size.size&url=https://deno.bundlejs.com/?q=fluent-vue&config={"esbuild":{"external":["vue"]}})
```
![](https://img.shields.io/badge/dynamic/json?label=fluent-vue&suffix=%20(bundlejs)&query=$.size.size&url=https://deno.bundlejs.com/?q=fluent-vue&config={"esbuild":{"external":["vue"]}})

Or breaks:
```md
![](https://img.shields.io/badge/dynamic/json?label=fluent-vue&suffix=%20(bundlejs)&query=$.size.size&url=https://deno.bundlejs.com/?q=fluent-vue%26config={"esbuild":{"external":["vue"]}})
```
![](https://img.shields.io/badge/dynamic/json?label=fluent-vue&suffix=%20(bundlejs)&query=$.size.size&url=https://deno.bundlejs.com/?q=fluent-vue%26config={"esbuild":{"external":["vue"]}})

**Comment by okikio** [comment]
You can use `encodeURIComponent(\`https://deno.bundlejs.com/?q=fluent-vue%26config={"esbuild":{"external":["vue"]}}\`)` to get a URL safe url,

e.g. `https%3A%2F%2Fdeno.bundlejs.com%2F%3Fq%3Dfluent-vue%2526config%3D%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22vue%22%5D%7D%7D` I don't do this by default, because it's just really difficult to read

**Comment by Demivan** [comment]
Yeah. I was trying to do that. But as you can see shields.io still complains.

But this is not an issue with bundlejs badges so this issue can be closed.

**Comment by okikio** [comment]
I'll look into what the best way to solve, and get back to you, for now I'll close this issue

**Comment by okikio** [comment]
@Demivan https://github.com/badges/shields/issues/9012
