### ISSUE TITLE
"browser" attribute in package.json is not used

### ISSUE THREAD

**Issue by danderson00** [okikio/bundlejs#31]
The `browser` attribute is generally used instead of the `src` attribute by bundlers such as webpack.

I also tried setting the `entryPoints` esbuild option but that did not work either.

Very useful tool, thanks!

**Comment by okikio** [comment]
Yeah, some of those features are currently broken, but I'm working on getting them working. Thanks 👍

**Comment by okikio** [comment]
@danderson00 Can you please send me a link to the package you're referring to. I want to confirm if the latest changes have solved this issue

**Comment by danderson00** [comment]
Awesome, you rock! @x/socket. I’ll give it a run at the end of the week. Skiing at the moment!😁

Thanks!

**Comment by okikio** [comment]
@danderson00 We're you able to solve the issue you had with bundlejs?

**Comment by okikio** [comment]
It seems this is fixed so I'll close this issue
