### ISSUE TITLE
mangleProps option value should be RegExp 

### ISSUE THREAD

**Issue by asvny** [okikio/bundlejs#35]
I guess the setting allows only JSON but when trying to provide a Regex for `mangleProps` it fails to build

**Comment by okikio** [comment]
How are you currently using `mangleProps`? Can you share a reproduction?

**Comment by okikio** [comment]
This should now be fixed in the latest version, with the addition of TS for configs

**Comment by okikio** [comment]
Seems fixed in production, I'll close this
