### ISSUE TITLE
Sharing with &bundle produces different results

### ISSUE THREAD

**Issue by Demivan** [okikio/bundlejs#37]
https://bundlejs.com/?q=fluent-vue&config={%22esbuild%22%3A{%22external%22%3A[%22vue%22]}}&bundle produces:

> ⌛ Bundled in 0.479 sec.
> Bundle size is 164.88KB -> 64.07KB (gzip)

https://bundlejs.com/?q=fluent-vue&config={%22esbuild%22%3A{%22external%22%3A[%22vue%22]}} and clicking "Build" manually produces:

> ⌛ Bundled in 0.104 sec.
> Bundle size is 13.16KB -> 4.63KB (gzip)

**Comment by okikio** [comment]
This should now be fixed
