### ISSUE TITLE
Error when downloading packages

### ISSUE THREAD

**Issue by fabian-hiller** [okikio/bundlejs#42]
bundlejs is exactly what I was looking for to show the benefits of my modular library. However, after I click on "build" an error occurs.

https://bundlejs.com/?q=%40modular-forms%2Fsolid&treeshake=%5B%7B+createForm%2CForm%2CField+%7D%5D

**Comment by okikio** [comment]
Sorry for the late response. You can use skypack.dev instead of unpkg.com https://bundlejs.com/?q=skypack%3A%40modular-forms%2Fsolid&treeshake=%5B%7B+createForm%2CForm%2CField+%7D%5D 

I've noticed an issue with bundlejs.com when using unpkg.com for `solidjs`, I'll investigate and try to fix it

**Comment by fabian-hiller** [comment]
Thank you! Now it works. Is there any way that bundlejs will also show the minified and gzipped version? Currently it is not minified or?

**Comment by fabian-hiller** [comment]
I think I made a mistake in my previous message. I thought bundlejs only shows me the bundle size of Modular Forms. After looking at it a bit closer, I assume that all dependencies are also included in the size specification. In this case everything is correct. Thanks for your work!

Maybe a graphical analysis in the style of the bundlejs website would be a cool feature for the future to be able to analyze the individual components even easier.

**Comment by okikio** [comment]
Yeah, can actually already do that https://bundlejs.com/?q=skypack%3A%40modular-forms%2Fsolid&treeshake=%5B%7B+createForm%2CForm%2CField+%7D%5D&config=%7B%22analysis%22%3Atrue%7D#analysis

**Comment by fabian-hiller** [comment]
Great. I find the UI of analysis built in so far not optimal. It cuts off the information on my package when hovering and the size information does not match the information above from bundlejs or am I missing something here? It shows 8 KB at the top and 27 KB in the analysis.

**Comment by okikio** [comment]
Yeah, I'm working on a new one based off of esbuilds bundle analyzer
