### ISSUE TITLE
Build client (browser) package version

### ISSUE THREAD

**Issue by thetarnav** [okikio/bundlejs#46]
I'm trying to get the size of client side bundle, but bundlejs keeps fetching server entries instead.
Is there a way to apply the browser export condition properly? I remember this working fine a while ago.

https://bundlejs.com/?q=%40solid-primitives%2Ftransition-group&config=%7B"esbuild"%3A%7B"minify"%3Afalse%2C"conditions"%3A%5B"browser"%5D%2C"external"%3A%5B"solid-js"%5D%7D%7D

![image](https://user-images.githubusercontent.com/24491503/226184020-c25974d8-03fc-4916-bfe5-4f5decfe95f4.png)

![image](https://user-images.githubusercontent.com/24491503/226184030-0018c9c5-d899-4da0-a39f-570bd01adbe9.png)

Here is how the export conditions are configured: https://github.com/solidjs-community/solid-primitives/blob/main/packages/transition-group/package.json
Haven't experienced issues with picking up the export conditions when bundling apps, but maybe I'm missing some convention?

**Comment by okikio** [comment]
Sorry, for the late response. Yeah, the bundlejs website isn't up to date yet, the API is more up to date, here is the result via the API ![](https://deno.bundlejs.com/?q=%40solid-primitives%2Ftransition-group&config=%7B%22esbuild%22%3A%7B%22minify%22%3Afalse%2C%22conditions%22%3A%5B%22browser%22%5D%2C%22external%22%3A%5B%22solid-js%22%5D%7D%7D&badge)

https://deno.bundlejs.com/?q=%40solid-primitives%2Ftransition-group&config=%7B%22esbuild%22%3A%7B%22minify%22%3Afalse%2C%22conditions%22%3A%5B%22browser%22%5D%2C%22external%22%3A%5B%22solid-js%22%5D%7D%7D&badge
