### ISSUE TITLE
Size reported of bundle is off

### ISSUE THREAD

**Issue by allain** [okikio/bundlejs#47]
It's reporting the following code bundles to a couple hundred bytes but it is closer to 10k or so.

```javascript
export {observer,computed, dispose} from "hyperactiv";
```

Reports:
`Bundle size is 174B -> 119B (gzip)`

When I enable analisys treemap, I can see that it's able to see the code defined though.

**Comment by okikio** [comment]
Sorry for the late response. `hyperactiv` only has a default export, so it's not able destructure properly when exporting 

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/17222836/235334192-bc482c2c-2d54-41f9-a608-34afe9ce6cb6.png">

The solution is to import the default export from `hyperactiv` first, then export the methods you'd like treeshaken

```ts
import hyperactiv from 'hyperactiv'
export const { observe, computed } = hyperactiv
```

[https://bundlejs.com/?q=hyperactiv&text="export+const+{observe,computed}+=+hyperactiv"](https://bundlejs.com/?q=hyperactiv&text="export+const+{observe,computed}+=+hyperactiv")
![](https://deno.bundlejs.com/badge?q=hyperactiv&text="export+const+{observe,computed}+=+hyperactiv")

**Comment by allain** [comment]
My apologies. I'd read and then forgot about it.

Thanks for replying

**Comment by okikio** [comment]
No worries 👍
