### ISSUE TITLE
Incorrent treeshake size in badge/API

### ISSUE THREAD

**Issue by crimx** [okikio/bundlejs#49]
The treeshake size in badge/API result is incorrect.

See [example](https://bundlejs.com/?q=value-enhancer&treeshake=%5B%7BisVal%2Csubscribe%7D%5D).

<img width="289" alt="image" src="https://github.com/okikio/bundlejs/assets/6882794/2d817ffe-d5d4-4b90-8a50-0f125027807e">

**Comment by okikio** [comment]
Yeah, that's a cache issue, I've now manually cleared it up but if you run into other cache issues like this if you give it a couple hours it will automatically clear up by itself, or you can take the badge url, and use the path /no-cache and it manually clear the cache and replace it with a new badge that's been generated `https://deno.bundlejs.com/no-cache?q=value-enhancer&treeshake=[{isVal,subscribe}]&config={%22analysis%22:undefined}&badge=`

**Comment by crimx** [comment]
Got it. `no-cache` works. I'll keep this issue open. You can close it whenever you feel it's appropriate.

**Comment by okikio** [comment]
Ok, then I'll close this issue
