### ISSUE TITLE
Possible badge caching issue

### ISSUE THREAD

**Issue by thoughtspile** [okikio/bundlejs#55]
I'm seeing suspicious "756 B" badges for various libraries when using `export *`, while the bundlejs console shows different results. looks like there might be some caching problem:
- [tinygesture](https://bundlejs.com/?q=tinygesture) ![](https://deno.bundlejs.com/badge?q=tinygesture)
- [quick-score](https://bundlejs.com/?q=quick-score) ![](https://deno.bundlejs.com/badge?q=quick-score)
- [fzy.js](https://bundlejs.com/?q=fzy.js) ![](https://deno.bundlejs.com/badge?q=fzy.js)

Here's a screenshot in case the cache gets busted:

<img width="281" alt="Снимок экрана 2023-07-13 в 14 13 27" src="https://github.com/okikio/bundlejs/assets/5262915/b0f7c230-f877-4dfb-98b1-c961a5e3c7ca">

The actual size of `fzy.js` is close to 756 bytes, I suspect it might be returned for the other libraries.

**Comment by yumauri** [comment]
Initially I thought, that badge API doesn't support `"external"`, but maybe I've stumbled at this issue as well
<img width="243" alt="image" src="https://github.com/okikio/bundlejs/assets/6583994/49452908-4d64-4f56-9f06-e20f35ccb3da">

**Comment by okikio** [comment]
@yumauri Yeah, this issue is closely related to the cache being too strongly held for badges, I might just end up removing caching for badges, since it seems to be causing these issues

**Comment by okikio** [comment]
@thoughtspile @yumauri I've drastically reduced caching so caching should be less of an issue now. Please try it out to confirm that the issue has been fixed

**Comment by yumauri** [comment]
Looks like there are no more caching issues in my case 👍

**Comment by thoughtspile** [comment]
I'm not seeing any duplicates either, thanks a ton 💜

**Comment by okikio** [comment]
Awesome 👍🏽 I'll mark this issue as complete then
