### ISSUE TITLE
Fetch the versions mentioned in package.json.

### ISSUE THREAD

**Issue by tyagirajat200** [okikio/bundlejs#56]
If I provide the complete package.json with dependencies, the code bundling process should fetch the versions mentioned in package.json instead of always fetching the latest version. Please guide me on the possible ways to achieve this.

Link -> [Click here](https://bundlejs.com/?q=react%2Creact-dom&treeshake=%5B*%5D%2C%5B*%5D&text=%22class+App+extends+Component+%7B%5Cn++constructor%28%29+%7B%5Cn++++super%28%29%3B%5Cn++++this.state+%3D+%7B%5Cn++++++name%3A+%27React%27%2C%5Cn++++%7D%3B%5Cn++%7D%5Cn%5Cn++render%28%29+%7B%5Cn++++return+%27Raj%27%3B%5Cn++%7D%5Cn%7D%22&config=%7B%22package.json%22%3A%7B%22dependencies%22%3A%7B%22react%22%3A%2217.0.2%22%2C%22react-dom%22%3A%2217.0.2%22%7D%7D%2C%22esbuild%22%3A%7B%22jsx%22%3A%22automatic%22%7D%7D)

**Comment by okikio** [comment]
Yeah, sorry that's a bug 🐛 😅, I'll try to get this fixed. In the meantime you can overcome this issue by manually setting the version for the module
E.g.
```ts
// Click Build for the Bundled, Minified & Compressed package size
export * from "react@17.0.2";
export * from "react-dom@17.0.2";
class App extends Component {
  constructor() {
    super();
    this.state = {
      name: 'React',
    };
  }

  render() {
    return 'Raj';
  }
}
```

**Comment by tyagirajat200** [comment]
Hi @okikio ,

Can the required code be included solely? For instance:
```javascript
import { zip } from 'https://unpkg.com/lodash-es@4.17.15/lodash.js';
console.log(zip([1, 2], ['a', 'b']));
```
In this scenario, the bundler should fetch and incorporate only the `zip` method from lodash, rather than including all of its methods, which is the current behavior.

**Comment by okikio** [comment]
It's because you're fetching from the URL, it's much harder to determine what to treeshake when a package is being fetched from a URL directly

Here is the fix,
```ts
// Click Build for the Bundled, Minified & Compressed package size
import { zip } from "lodash-es@4.17.15";
console.log(zip([1, 2], ['a', 'b']))
```

Link -> https://bundlejs.com/?q=(import)lodash-es@4.17.15&treeshake={+zip+}&text="console.log(zip([1,+2],+['a',+'b']))"
