### ISSUE TITLE
Generates an incorrect URL for a Redux Toolkit nested entry point

### ISSUE THREAD

**Issue by markerikson** [okikio/bundlejs#58]
I'm trying to bundle this set of exports:

```ts
export { configureStore } from "@reduxjs/toolkit";
export {createApi} from "@reduxjs/toolkit/query/react";
export { Provider } from "react-redux";
```

It downloads React-Redux okay, but fails to download the RTK `/query/react` entry point, because it's generating a wrong version URL (`1.0.0`, when the current version is `1.9.5`):

```
✘ [ERROR] Do not know how to load path: http-url:https://unpkg.com/@reduxjs/toolkit@1.0.0/dist/query/react/rtk-query-react.esm.js


/input.ts:2:24:

      2 │ export {createApi} from "@reduxjs/toolkit/query/react";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by okikio** [comment]
This is an issue with the `package.json` of `@reduxjs/toolkit`

https://unpkg.com/@reduxjs/toolkit@1.9.7/query/react/package.json
```json
{
    "name": "@reduxjs/toolkit-query-react",
    "version": "1.0.0",
    "description": "",
    "main": "../../dist/query/react/index.js",
    "module": "../../dist/query/react/rtk-query-react.esm.js",
    "unpkg": "../../dist/query/react/rtk-query-react.umd.min.js",
    "author": "Mark Erikson <mark@isquaredsoftware.com>",
    "license": "MIT",
    "types": "../../dist/query/react/index.d.ts",
    "sideEffects": false
}
```

The version mismatch confuses `bundlejs`, I'm thinking about what the best solution for this would be? 🤔

**Comment by markerikson** [comment]
Hmm. Yeah, part of the problem here is that this is actually all one package, with multiple entry points.  That `package.json` file only exists so that alternate entry points work with Node's existing resolution algorithm.

The version numbers in those are pretty irrelevant, but technically I could update those as part of the build process, I guess.

RTK 2.0 has proper ESM and `package.exports` support, so that should improve things.

But, both these attempts error in different ways:

```ts
export { configureStore } from "@reduxjs/toolkit@2.0.0-beta.4";
export {createApi} from "@reduxjs/toolkit@2.0.0-beta.4/query/react";
// or
// export {createApi} from "@reduxjs/toolkit/query/react@2.0.0-beta.4";
export { Provider } from "react-redux";
```

**Comment by okikio** [comment]
I'll look into way to fix that behaviour

**Comment by okikio** [comment]
Sorry, about that, this should now be fixed, please give it a try

**Comment by markerikson** [comment]
Awesome, that works now - thank you!

![image](https://github.com/okikio/bundlejs/assets/1128784/82a4d147-542a-4995-bda1-79ea9b8a8b24)
