### ISSUE TITLE
no longer works by default (with unpkg)

### ISSUE THREAD

**Issue by NullVoxPopuli** [okikio/bundlejs#60]
https://bundlejs.com/?q=active-inflector&treeshake=%5B*%5D

## FireFox 
![image](https://github.com/okikio/bundlejs/assets/199018/26b37fe8-27fa-4f37-9dc2-be125257f82d)

![image](https://github.com/okikio/bundlejs/assets/199018/cca82bc3-557a-4b75-b2fa-d6046e10d87b)

## Chrome
![image](https://github.com/okikio/bundlejs/assets/199018/4bbf5870-ca90-4cf1-af43-e10e0245c33f)

![image](https://github.com/okikio/bundlejs/assets/199018/0a29fb20-282f-4860-ac94-665230491238)

**Comment by NullVoxPopuli** [comment]
choosing other CDNs appears to have no effect

for example: https://bundlejs.com/?q=active-inflector&treeshake=%5B*%5D&config=%7B%22cdn%22%3A%22https%3A%2F%2Fcdn.esm.sh%22%7D

still builds with unpkg

**Comment by NullVoxPopuli** [comment]
this URL works: https://bundlejs.com/?q=active-inflector&treeshake=%5B*%5D&config=%7B%22cdn%22%3A%22esm.run%22%2C%22esbuild%22%3A%7B%22logLevel%22%3A%22debug%22%7D%7D

**Comment by okikio** [comment]
Unpkg.com seemed to have gone down for a bit there, its now fixed, but you're right about the bug where it's not switching CDNs, I've  been working on fixing it for sometime, I just haven't had much time thus recently

**Comment by okikio** [comment]
This issue was fixed a while back but I forgot it
