### ISSUE TITLE
[FIXED] Cross-Origin Read Blocking made the badges unavailable on Github Readmes

### ISSUE THREAD

**Issue by EDM115** [okikio/bundlejs#62]
The issue seems to be fixed (now) but I wanted to tell you that it happened yesterday, and I'm curious to know what caused it 👀   
  
Screenshots : https://github.com/jazzypants1989/jessquery/issues/5

**Comment by okikio** [comment]
Oh, interesting 🤔

**Comment by EDM115** [comment]
as both urls (yours and GitHub camo ones) displayed things, it may also be an issue on GitHub’s side 🤷‍♂️  
tho idk where to open an issue for this

**Comment by okikio** [comment]
Yeah, this seems like either a github issue or a Deno Deploy issue 🤷🏽
