### ISSUE TITLE
[SECURITY VULNERABILITY] In your codebase is a reference of the cdn com polyfill com io service

### ISSUE THREAD

**Issue by PriNova** [okikio/bundlejs#71]
https://github.com/okikio/bundlejs/blob/55ac6fed60d9f86656e0b6d318052508b90b05bc/src/assets/_headers#L18

This file is using the cdn.polyfill.io service which is known for injecting malicious code

Please use the cloudflare polyfill service

https://x.com/WeldPond/status/1805973940642119900

**Comment by okikio** [comment]
Thanks for the find, I stopped using polyfill.io a couple years ago I just commented it out at the time, but I guess I hadn't removed the old comments. I've now removed all references to polyfill.io
