### ISSUE TITLE
Fails with "too much recursion" on @ensdomains/ensjs@3.7.0

### ISSUE THREAD

**Issue by talentlessguy** [okikio/bundlejs#72]
Input:

```
// Click Build for the Bundled, Minified & Compressed package size
export * from "@ensdomains/ensjs@3.7.0";
```

Output:

```
Fetch https://unpkg.com/es-abstract@1.23.3/2024/StringToBigInt.js

✘ [ERROR] too much recursion [plugin http-url]

http-url:https://unpkg.com/@ensdomains/address-encoder@1.1.1/dist/esm/coins.js:56:21:

      56 │ export { iost } from "./coin/iost.js";
         ╵                      ~~~~~~~~~~~~~~~~
```

**Comment by okikio** [comment]
I just tried running the build, it seemed to work with no errors, it could be a potential cache error, try running the build again in Incognito mode

![CleanShot 2024-06-29 at 01 59 21@2x](https://github.com/okikio/bundlejs/assets/17222836/2f2dbdb9-cdd7-412e-a2bf-26cd108d07d2)

**Comment by talentlessguy** [comment]
I cleared browser cache and it builds now, not sure what it was before
