### ISSUE TITLE
Add package size

### ISSUE THREAD

**Issue by artalar** [okikio/bundlejs#76]
The size of a bundle is one of the most important aspects of a package. However, there is another aspect of package quality that can affect the DX and CI process - the size of the package installation, which depends on the number of files loaded and the size of third-party dependencies. It would be useful to display this size in the build output.

A similar project: https://packagephobia.com/.

**Comment by okikio** [comment]
Publish size has now been added as a feature, thanks 👍🏽

**Comment by artalar** [comment]
Awesome! Thank you!
