### ISSUE TITLE
 No matching export `toSignal`

### ISSUE THREAD

**Issue by crutchcorn** [okikio/bundlejs#77]
With the following input:

```typescript
export { createAction,  createReducer, on, StoreModule, createSelector } from '@ngrx/store';
```

I get the following error:

✘ [ERROR] No matching export in "http-url:[https://unpkg.com/@angular/core@18.0.2/rxjs-interop/index.d.ts"](https://unpkg.com/@angular/core@18.0.2/rxjs-interop/index.d.ts%22); for import "toSignal"

Despite there being an export in @angular/core/rxjs-interop for `toSignal` in that file:

![image](https://github.com/user-attachments/assets/fdc9114e-1873-4fff-85eb-4e002789875c)

**Comment by okikio** [comment]
Interesting, I'll take a quick look

**Comment by okikio** [comment]
This should now be fixed, please take a look [bundlejs.com/?q=@ngrx/store&treeshake=\[{+createAction,createReducer,on,StoreModule,createSelector+}\]](https://bundlejs.com/?q=%40ngrx%2Fstore&treeshake=%5B%7B+createAction%2CcreateReducer%2Con%2CStoreModule%2CcreateSelector+%7D%5D)

**Comment by crutchcorn** [comment]
Works great! Thank you!
