### ISSUE TITLE
Fetching incorrect entry file from unpkg.com

### ISSUE THREAD

**Issue by crimx** [okikio/bundlejs#79]
Here is an simple example package [adaptive-set](https://hyrious.me/npm-browser/?q=adaptive-set@0.1.2/package/package.json). It exports both cjs and esm.

```json
{
  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
}
```

1. bundlejs with `"cdn": "https://unpkg.com",` config ([link](https://bundlejs.com/?q=adaptive-set&treeshake=%5B*%5D))
   fetches the cjs entry `Fetch https://unpkg.com/adaptive-set@0.1.2/dist/index.js` (501 B (gzip)).
2. bundlejs with `"cdn": "https://esm.sh",` config ([link](https://bundlejs.com/?q=adaptive-set&treeshake=%5B*%5D&config=%7B%22cdn%22%3A%22https%3A%2F%2Fesm.sh%22%7D))
   fetches the correct esm entry `Fetch https://esm.sh/v135/adaptive-set@0.1.2/es2022/adaptive-set.mjs` (203 B (gzip)).
 
 Anthor bug. It seems like the badge result generated by custom config does not work. It always points to the reuslt generated by the default config. (501 B (gzip))

[deno.bundlejs.com/badge?q=adaptive-set&treeshake=[*]&config={"cdn":"https://esm.sh"}](https://deno.bundlejs.com/badge?q=adaptive-set&treeshake=[*]&config={%22cdn%22:%22https://esm.sh%22})

**Comment by okikio** [comment]
This should now be fixed. With regards to the caching I've reduced the strictness of caching. 👍🏽
