### ISSUE TITLE
Replace denoflate by native compression Streams API

### ISSUE THREAD

**Issue by SirMishaa** [okikio/bundlejs#80]
Hello ! 

The denoflate packaged is deprecated in flavor of [native API of browser](https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream/CompressionStream). 

Would it make sense to replace the use of this package in order to reduce the size of the JS bundle?

**Comment by okikio** [comment]
😅 I switched a couple years ago, I guess I forgot to update the README
